JiffyBag.configure %w{
  MONGOID_ENVIRONMENT
  GA_TRACKER_ID
  GA_DOMAIN
  BUGHERD_PROJECT_KEY
  AWS_ACCESS_KEY
  AWS_SECRET_ACCESS_KEY
  AWS_BUCKET
  OPENSPACE_API_KEY
  LEGATO_OAUTH_REFRESH_TOKEN
  LEGATO_OAUTH_CLIENT_ID
  LEGATO_OAUTH_SECRET_KEY
}
